version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: examplepassword
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:examplepassword@db:5432/mydb
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    restart: always

volumes:
  pgdata:
